server: 
  port: 8080
  contextPath: /garage
  #https
  tomcat: 
    remote_ip_header: x-forwarded-for
    protocol_header: x-forwarded-proto
    port-header: X-Forwarded-Port
  use-forward-headers: true
spring:
#  profiles:
#    active: ${spring.active}
  application: 
    name: garage-server
  datasource: 
    url: jdbc:mysql://10.0.91.108:5506/safegarage?autoReconnect=true&useUnicode=true&characterEncoding=utf8&useSSL=false&zeroDateTimeBehavior=convertToNull&serverTimezone=CTT
    username: safegarage_writer
    password: Safe^d(df68)dfYiUk
    driverClassName: com.mysql.jdbc.Driver
    filters: wall,mergeStat
    logSlowSql: true
  redis:
    cluster:
      nodes: dsj_redis01:6379,dsj_redis02:6379,dsj_redis03:6379,dsj_redis04:6379,dsj_redis05:6379,dsj_redis06:6379
    pool: 
      max-active: 100
      max-idle: 10
      max-wait: 1
      min-idle: 2
  session: 
    store-type: none
  rabbitmq: 
    addresses: 10.0.4.75:5672,10.0.4.76:5672,10.0.4.77:5672
    vHost: rentcar_pro
    username: guest
    password: guest
yixin: 
  projectName: ${spring.application.name}
      
mybatis-plus:
  mapper-locations:
    - classpath:/mapper/*.xml
  type-aliases-package: com.yixin.garage.entity
  global-config: 
    refresh: true
    db-config: 
      id-type: id_worker  #全局默认主键类型
      #逻辑已删除值,(逻辑删除下有效)
      logic-delete-value: 1
      logic-not-delete-value: 0
      field-strategy: ignored
  configuration: 
    cache-enabled: true  #该配置影响的所有映射器中配置的缓存的全局开关
    lazyLoadingEnabled: true #全局性设置懒加载。如果设为‘false’，则所有相关联的都会被初始化加载。
    aggressive-lazy-loading: true  #将积极加载改为消极加载及按需加载 
    logImpl: org.apache.ibatis.logging.slf4j.Slf4jImpl # 打印sql语句,不打sql时请注释该行配置


garage:
  spring-session-open: false      #是否开启spring session,如果是多机环境需要开启(true/false)
  session-invalidate-time: 1800     #session失效时间(只在单机环境下生效，多机环境在SpringSessionConfig类中配置) 单位：秒
  session-validation-interval: 900  #多久检测一次失效的session(只在单机环境下生效) 单位：秒
  swagger-open: false #生产设置关闭
  cache: 
    enable: true #是否开启缓存
    type: redisCacheManager # 可选参数： ehCacheCacheManager | redisCacheManager, 该项不配置时两个CacheManager都创建，primary为redisCacheManager
  sql-performance-enable: flase # 是否开启 SQL执行效率插件
env: pro
    
log:
  path: garage-logs

shiro:
  casServerUrlPrefix: https://oacas.yixincapital.com/casserver
  casService: https://safe-garage.yxqiche.com/garage/shiro-cas
  casServerList: https://10.0.3.61:8080/garage/shiro-cas,https://10.0.3.62:8080/garage/shiro-cas

#USC config
usc:
  getAdjunctByDomainAccountAndSystemId: https://usc.yixincapital.com/nusc-web/api/otherService/getAdjunctByDomainAccountAndSystemId
  findResourceByUser: https://usc.yixincapital.com/nusc-web/api/otherService/findResourceByUser
  getPermissionByDomainAccountAndSystemId1: https://usc.yixincapital.com/nusc-web/api/userDubboService/getPermissionByDomainAccountAndSystemId1
  getUsersInfoByRoleId: https://usc.yixincapital.com/nusc-web/api/userDubboService/getUsersInfoByRoleId?roleId=
  getUserInfoByDomainAccount: https://usc.yixincapital.com/nusc-web/api/userDubboService/getUserInfoByDomainAccount?domainAccount=
  nuscWebApi: https://usc.yixincapital.com/nusc-web/api/
  getUserByPhoneNO: https://usc.yixincapital.com/nusc-web/api/userDubboService/getUserByPhoneNO?phoneNO=
  systemId: 10288  #用户中心系统id

basedata:
  basedataURL: https://basedata.yixincapital.com
  getSubRegionsUrl: /basedata/api/basicRegion/getSubRegions
  getProvincesUrl: /basedata/api/basicRegion/getProvinces



# 生产角色id待配置
loan:
  editRole: 4521
  checkRole: 4524
  #融资大区总监
  partmentRole: 4522
  #资金管理部操作员
  ziguanRole: 4524
  ziguanJingliRole: 4526
  ziguanLeaderRole: 4525
role: 
  financing: 
      BD: 4521 #融资BD
      areaLeader: 4522 #融资大区总监
      fundOperator: 4524 #资金管理部操作员
      fundDirector: 4526 #资金管理部总监
      fundPIC: 4525 #资金管理部负责人
      chairman: 4523 #总裁
  CFO: 4528
fund:
   partmentRole: 4525
   vpRole: 4523
   editRole: 4524
   submitRole: 4527
   partmentJingliRole: 4526


garageRole:
   garageManageRoleId: 4773 #安全车库 - 车库管理员
   disposeCommissionerRoleId: 4774 #安全车库 - 自建库处置专员
   assetsCommissionerRoleId: 4775 #安全车库 - 资产经理
   garageChecklistRoleId: 4814 #安全车库 - 车库一览


   

#msgCenter config
msgCenter: https://messagecenter.yixincapital.com/mc/yxMessage/send
mailfrom: 易鑫车商金服部<yixinkp@notice.daikuan.com>
mailTo : lidezhi@yxqiche.com
mailCc: qiaoxincheng02@yxqiche.com

#邮件格式
mailFormat: msg,eml

#文件服务器地址
fileServiceURL: https://fileserver.yixincapital.com
#文件服务器地址（展示图片用）
fileServerUrl: https://fileserverinter.yxqiche.com
#查看图片
viewFileServerPath: http://filestore.yixincapital.com/
  
#获取银企日滚动数据地址
paymentData: 
  url: http://tms.yxqiche.com/payment/dataManage/countInfo
  
#获取中台日滚动数据地址
ztDayData: 
  url: http://zeus.yxqiche.com/hscsm/api/public/day/flow/selectDataByDay
#获取中台月滚动数据地址
ztMonthData: 
  url: http://zeus.yxqiche.com/hscsm/api/public/month/flow/selectDataByMonth

#车型库
carStyleUrl: https://vehicletypelib-web.yixincapital.com/vehicletypelib-web/api

#中台url
sgToErpUrl: https://zeus.yxqiche.com/hscsm

fileContextPath: /data1/d_info/garage-server/

#进销存
rentCarUrl: https://rentcar-web.yixincapital.com/rentcar-web/